[2024-02-27T10:12:12.453+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.load_prod_elect_dept manual__2024-02-27T10:11:40.082480+00:00 [queued]>
[2024-02-27T10:12:12.547+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.load_prod_elect_dept manual__2024-02-27T10:11:40.082480+00:00 [queued]>
[2024-02-27T10:12:12.558+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-02-27T10:12:12.654+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_prod_elect_dept> on 2024-02-27 10:11:40.082480+00:00
[2024-02-27T10:12:12.707+0000] {standard_task_runner.py:57} INFO - Started process 14928 to run task
[2024-02-27T10:12:12.872+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'load_prod_elect_dept', 'manual__2024-02-27T10:11:40.082480+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpzfikyy6t']
[2024-02-27T10:12:12.917+0000] {standard_task_runner.py:85} INFO - Job 612: Subtask load_prod_elect_dept
[2024-02-27T10:12:13.400+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.load_prod_elect_dept manual__2024-02-27T10:11:40.082480+00:00 [running]> on host 952b3f8a1a94
[2024-02-27T10:12:13.773+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='load_prod_elect_dept' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T10:11:40.082480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T10:11:40.082480+00:00'
[2024-02-27T10:12:13.783+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:198: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2024-02-27T10:12:19.560+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 110, in load_prod_elect_dept
    kwargs['task_instance'].xcom_push(key='df_prod_elect_dept', value=df_prod_elect_dept)
NameError: name 'kwargs' is not defined
[2024-02-27T10:12:19.587+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=EnergyWarehouse, task_id=load_prod_elect_dept, execution_date=20240227T101140, start_date=20240227T101212, end_date=20240227T101219
[2024-02-27T10:12:19.623+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 612 for task load_prod_elect_dept (name 'kwargs' is not defined; 14928)
[2024-02-27T10:12:19.683+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-02-27T10:12:19.812+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
