[2024-03-10T20:55:44.107+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_region manual__2024-03-10T20:46:17.709120+00:00 [queued]>
[2024-03-10T20:55:44.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_region manual__2024-03-10T20:46:17.709120+00:00 [queued]>
[2024-03-10T20:55:44.138+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:55:44.171+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_region> on 2024-03-10 20:46:17.709120+00:00
[2024-03-10T20:55:44.185+0000] {standard_task_runner.py:57} INFO - Started process 2517 to run task
[2024-03-10T20:55:44.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_region', 'manual__2024-03-10T20:46:17.709120+00:00', '--job-id', '965', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmp7cd31siu']
[2024-03-10T20:55:44.206+0000] {standard_task_runner.py:85} INFO - Job 965: Subtask create_dim_region
[2024-03-10T20:55:44.305+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_region manual__2024-03-10T20:46:17.709120+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:55:44.494+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_region' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T20:46:17.709120+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T20:46:17.709120+00:00'
[2024-03-10T20:55:44.521+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 330, in create_dim_region
    region_dim = df_conso_energy_dept[['code_region' , 'libelle_region' ]].drop_duplicates().reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
[2024-03-10T20:55:44.543+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_region, execution_date=20240310T204617, start_date=20240310T205544, end_date=20240310T205544
[2024-03-10T20:55:44.570+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 965 for task create_dim_region ('NoneType' object is not subscriptable; 2517)
[2024-03-10T20:55:44.611+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T20:55:44.686+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
