[2024-03-10T20:37:51.808+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_domaine_tension manual__2024-03-10T20:20:36.100743+00:00 [queued]>
[2024-03-10T20:37:51.852+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: EnergyWarehouse.create_dim_domaine_tension manual__2024-03-10T20:20:36.100743+00:00 [queued]>
[2024-03-10T20:37:51.857+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-03-10T20:37:51.902+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): create_dim_domaine_tension> on 2024-03-10 20:20:36.100743+00:00
[2024-03-10T20:37:51.928+0000] {standard_task_runner.py:57} INFO - Started process 1971 to run task
[2024-03-10T20:37:51.942+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'EnergyWarehouse', 'create_dim_domaine_tension', 'manual__2024-03-10T20:20:36.100743+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/***-to-bigquery-dag/***_to_bigquerry_dag.py', '--cfg-path', '/tmp/tmpifx8bhv9']
[2024-03-10T20:37:51.953+0000] {standard_task_runner.py:85} INFO - Job 918: Subtask create_dim_domaine_tension
[2024-03-10T20:37:52.148+0000] {task_command.py:410} INFO - Running <TaskInstance: EnergyWarehouse.create_dim_domaine_tension manual__2024-03-10T20:20:36.100743+00:00 [running]> on host 952b3f8a1a94
[2024-03-10T20:37:52.449+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mbaye SENE' AIRFLOW_CTX_DAG_ID='EnergyWarehouse' AIRFLOW_CTX_TASK_ID='create_dim_domaine_tension' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T20:20:36.100743+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T20:20:36.100743+00:00'
[2024-03-10T20:37:52.488+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/airflow-to-bigquery-dag/airflow_to_bigquerry_dag.py", line 235, in create_dim_domaine_tension
    domaine_tension = df_prod_elec_region[['domaine_de_tension']].drop_duplicates().reset_index(drop=True)
TypeError: 'NoneType' object is not subscriptable
[2024-03-10T20:37:52.514+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=EnergyWarehouse, task_id=create_dim_domaine_tension, execution_date=20240310T202036, start_date=20240310T203751, end_date=20240310T203752
[2024-03-10T20:37:52.556+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 918 for task create_dim_domaine_tension ('NoneType' object is not subscriptable; 1971)
[2024-03-10T20:37:52.615+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-03-10T20:37:53.067+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
